---
title: "p8105_hw6_zj2357"
author: "Zekai Jin (zj2357)"
date: "2022-11-29"
output: github_document
---

First of all, we should include the libraries we are using.
```{r init, message=FALSE}
library(tidyverse)
library(p8105.datasets)
library(patchwork)
library(modelr)
library(ggridges)

knitr::opts_chunk$set(
  message  = FALSE,
  warning = FALSE,
  fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
```

# Problem 1
Downloading the dataset
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
boot_straps = 
  tibble(
    strap_num = 1:100,
    strap_samp = rerun(100, sample_frac(weather_df, replace = TRUE))
  ) %>%
  mutate(
    models = map(.x=strap_samp, ~lm(tmax~tmin, data = .x)),
    beta = map(.x=models,~pull(broom::tidy(.x),estimate)),
    rsq =  map(.x=models,~pull(broom::glance(.x),r.squared)),
    beta_sq = map(beta,prod)
  ) %>%
  select(strap_num,rsq,beta_sq) %>%
  mutate(
      rsq = as.numeric(rsq),
      beta_sq = as.numeric(beta_sq)
  )
```

plotting
```{r}
rsq_plot = 
  boot_straps %>%
  ggplot(aes(x=rsq)) +
  geom_density() +
  xlab("x square")

beta_plot = 
  boot_straps %>%
  ggplot(aes(x=beta_sq)) +
  geom_density() +
  xlab("beta_0 times beta_1 ")

beta_plot + rsq_plot


```

CI
```{r}
conf_int =
  boot_straps %>%
  pivot_longer(
    rsq:beta_sq,
    names_to = "variable",
    values_to = "value"
  ) %>%
  group_by(variable) %>%
  summarise(
    lower_CI = quantile(value,0.025),
    higher_CI = quantile(value,0.975)
  )
conf_int
```

# Problem 2
```{r}
rm(list = ls())

homi_df = 
  read_csv("data/homicide-data.csv") %>%
  mutate(
    city_state = str_c(city, ", ", state),
    solved = !disposition %in% c("Closed without arrest","Open/No arrest"),
    victim_age = as.numeric(victim_age)
  ) %>%
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
    victim_race %in% c("Black", "White")
  ) %>%
  select(uid,city_state,solved,victim_race, victim_age, victim_sex) %>%
  na.omit()



```


`Baltimore, MD`
```{r}
logi_fit = 
  homi_df %>%
  filter(city_state == "Baltimore, MD") %>%
  glm(solved~ victim_race+ victim_age+ victim_sex, data = ., family = "binomial")

logi_fit %>%
  broom::tidy() %>%
  filter(term == "victim_sexMale") %>%
  mutate(
    conf_low = estimate-1.96*std.error,
    conf_high = estimate+1.96*std.error
  )  %>%
  select(term,estimate,conf_low,conf_high)

```

other cities


```{r}
logi_fit =
  homi_df %>%
  nest(data = c(uid,solved, victim_age,victim_race,victim_sex)) %>%
  mutate(
    model = map(.x = data, ~glm(solved~ victim_race+ victim_age+ victim_sex, data = .x, family = "binomial")),
    estimate = map(.x=model, ~filter(broom::tidy(.x),term == "victim_sexMale"))
  ) %>%
  unnest(estimate) %>%
  mutate(
    conf_low = estimate-1.96*std.error,
    conf_high = estimate+1.96*std.error
  )  %>%
  select(city_state,estimate,conf_low,conf_high)

logi_fit
```

plotting

```{r}
logi_fit %>%
  mutate(
    city_state = fct_reorder(city_state, -estimate)
  ) %>%
  ggplot(aes(x = estimate, y = city_state)) +
  geom_point() +
  geom_errorbar(aes(xmin = conf_low, xmax = conf_high)) +
  labs(title = "Odds ratio of solved cases between male and female victims")
```

Thus, in most cities, after adjusting for race and age, cases with male victims have more odds to be unsolved.


# Problem 3

```{r}
rm(list = ls())

racelist = c("white","black", "asian", "puerto rican", "other", "unknown")
birth_df = 
  read_csv("data/birthweight.csv") %>%
  na.omit() %>%
  mutate(
    babysex = factor(babysex, levels = 1:2, labels = c("male","female")),
    frace = factor(frace, levels = c(1,2,3,4,8,9),labels= c("white","black", "asian", "puerto rican", "other", "unknown")),
    mrace = factor(mrace, levels = c(1,2,3,4,8),labels= c("white","black", "asian", "puerto rican", "other")),
    malform = factor(malform, levels = 0:1,labels = c("absent","present"))
  ) %>%
  select(bwt, everything())
  

```



building my model
```{r}
model_mine = step(lm(bwt ~ ., data = birth_df),direction = "both",trace = 0)

formula_mine=formula(model_mine)
formula_mine
```

plotting
```{r}
birth_df %>%
  add_predictions(model_mine) %>%
  add_residuals(model_mine) %>%
  ggplot(aes(x=pred,y=resid)) +
  geom_point() +
  labs(title = "residule vs predicted outcomes")
```


other models
```{r}
model_1 = lm(bwt ~ blength+ gaweeks,data = birth_df)
model_2 = lm(bwt ~ (bhead+ blength +babysex)^3,data = birth_df)
```




cross validation
```{r}
cv_df = 
  crossv_kfold(birth_df, k=10) %>%
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  ) %>%
  mutate(
    mod_mine = map(train, ~lm(formula_mine,data = .x)),
    mod_1 = map(train, ~lm(bwt ~ blength+ gaweeks,data = .x)),
    mod_2 = map(train, ~lm(bwt ~ (bhead+ blength +babysex)^3,data = .x))
  ) %>%
  mutate(
    rmse_mine = map2_dbl(mod_mine, test, ~rmse(model=.x,data=.y)),
    rmse_1 = map2_dbl(mod_1, test, ~rmse(model=.x,data=.y)),
    rmse_2 = map2_dbl(mod_2, test, ~rmse(model=.x,data=.y)),
  )

```

ploting

```{r}
cv_df %>%
  select(.id,rmse_mine,rmse_1,rmse_2) %>%
  pivot_longer(
    rmse_mine:rmse_2,
    names_to = "model",
    names_prefix = "rmse_",
    values_to = "rmse"
  ) %>%
  ggplot(aes(x=rmse,y=model,fill=model)) +
  geom_density_ridges() +
  labs(title = "distribution of rmse  under  different model")
```




